CREATE DATABASE IF NOT EXISTS app_db;

USE app_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (name, email, password) VALUES
    ('Alice Smith', 'alice1@example.com', 'password1'),
    ('Bob Jones', 'bob2@example.com', 'password2'),
    ('Carol Lee', 'carol3@example.com', 'password3'),
    ('David Kim', 'david4@example.com', 'password4'),
    ('Eve Clark', 'eve5@example.com', 'password5'),
    ('Frank Hall', 'frank6@example.com', 'password6'),
    ('Grace Young', 'grace7@example.com', 'password7'),
    ('Hank King', 'hank8@example.com', 'password8'),
    ('Ivy Scott', 'ivy9@example.com', 'password9'),
    ('Jack White', 'jack10@example.com', 'password10'),
    ('Kara Black', 'kara11@example.com', 'password11'),
    ('Leo Green', 'leo12@example.com', 'password12'),
    ('Mona Reed', 'mona13@example.com', 'password13'),
    ('Nate Wood', 'nate14@example.com', 'password14'),
    ('Olga Fox', 'olga15@example.com', 'password15'),
    ('Paul Gray', 'paul16@example.com', 'password16'),
    ('Quinn Day', 'quinn17@example.com', 'password17'),
    ('Rita Lane', 'rita18@example.com', 'password18'),
    ('Sam Page', 'sam19@example.com', 'password19'),
    ('Tina Cole', 'tina20@example.com', 'password20'),
    ('Uma Bell', 'uma21@example.com', 'password21'),
    ('Vince Ray', 'vince22@example.com', 'password22'),
    ('Wendy Nash', 'wendy23@example.com', 'password23'),
    ('Xander Poe', 'xander24@example.com', 'password24'),
    ('Yara Moss', 'yara25@example.com', 'password25'),
    ('Zane Wolf', 'zane26@example.com', 'password26'),
    ('Amy Park', 'amy27@example.com', 'password27'),
    ('Ben Ford', 'ben28@example.com', 'password28'),
    ('Cora West', 'cora29@example.com', 'password29'),
    ('Drew Snow', 'drew30@example.com', 'password30'),
    ('Elle Moon', 'elle31@example.com', 'password31'),
    ('Finn Lake', 'finn32@example.com', 'password32'),
    ('Gina Rose', 'gina33@example.com', 'password33'),
    ('Hugo Star', 'hugo34@example.com', 'password34'),
    ('Iris Dale', 'iris35@example.com', 'password35'),
    ('Jude Frost', 'jude36@example.com', 'password36'),
    ('Kian Pike', 'kian37@example.com', 'password37'),
    ('Lila Snow', 'lila38@example.com', 'password38'),
    ('Mick Blue', 'mick39@example.com', 'password39'),
    ('Nina Gold', 'nina40@example.com', 'password40'),
    ('Omar Finn', 'omar41@example.com', 'password41'),
    ('Pia Lane', 'pia42@example.com', 'password42'),
    ('Rex Ford', 'rex43@example.com', 'password43'),
    ('Sia Moss', 'sia44@example.com', 'password44'),
    ('Toby Nash', 'toby45@example.com', 'password45'),
    ('Ula Poe', 'ula46@example.com', 'password46'),
    ('Vera Wolf', 'vera47@example.com', 'password47'),
    ('Will Park', 'will48@example.com', 'password48'),
    ('Xena Ford', 'xena49@example.com', 'password49'),
    ('Yuri West', 'yuri50@example.com', 'password50');
