// File generated by flutterfire_cli.
// With modifications for manual Firebase setup
// Replace the placeholder values with your actual Firebase config from Google Cloud Console

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb0U81DeLytecyiCII7Nz_c6H6-BxUwEs',
    authDomain: 'fureverhome-80125.firebaseapp.com',
    projectId: 'fureverhome-80125',
    storageBucket: 'fureverhome-80125.firebasestorage.app',
    messagingSenderId: '898168123216',
    appId: '1:898168123216:web:6ee6e17f53191dd4c8c655',
    measurementId: 'G-B4FM9LZVYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb0U81DeLytecyiCII7Nz_c6H6-BxUwEs',
    appId: '1:898168123216:android:6ee6e17f53191dd4c8c655',
    messagingSenderId: '898168123216',
    projectId: 'fureverhome-80125',
    storageBucket: 'fureverhome-80125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1_Z9pQ1r2s3t4u5v6w7x8y9z0-def1234',
    appId: '1:123456789012:ios:abc1234567890def',
    messagingSenderId: '123456789012',
    projectId: 'fureverhome-80125',
    storageBucket: 'fureverhome-80125.appspot.com',
    iosBundleId: 'com.example.adoptADog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1_Z9pQ1r2s3t4u5v6w7x8y9z0-def1234',
    appId: '1:123456789012:ios:abc1234567890def',
    messagingSenderId: '123456789012',
    projectId: 'fureverhome-80125',
    storageBucket: 'fureverhome-80125.appspot.com',
    iosBundleId: 'com.example.adoptADog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb0U81DeLytecyiCII7Nz_c6H6-BxUwEs',
    appId: '1:898168123216:web:6ee6e17f53191dd4c8c655',
    messagingSenderId: '898168123216',
    projectId: 'fureverhome-80125',
    storageBucket: 'fureverhome-80125.firebasestorage.app',
    measurementId: 'G-B4FM9LZVYL',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAb0U81DeLytecyiCII7Nz_c6H6-BxUwEs',
    appId: '1:898168123216:web:6ee6e17f53191dd4c8c655',
    messagingSenderId: '898168123216',
    projectId: 'fureverhome-80125',
    storageBucket: 'fureverhome-80125.firebasestorage.app',
    measurementId: 'G-B4FM9LZVYL',
  );

  /// Get the appropriate Firebase options for the current platform
  static FirebaseOptions get currentPlatform {
    // Web platform
    if (const bool.fromEnvironment('dart.library.js_util')) {
      return web;
    }
    // Mobile/Desktop platforms
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.fuchsia:
        break;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }
}
